// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0JGMXkp4UXO08kKu8FxC3ap0wUkWV68o',
    appId: '1:361449298229:web:f18f9db94270512e2b147c',
    messagingSenderId: '361449298229',
    projectId: 'furniture-hub-b0293',
    authDomain: 'furniture-hub-b0293.firebaseapp.com',
    storageBucket: 'furniture-hub-b0293.firebasestorage.app',
    measurementId: 'G-V3919TR53N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlfbwitOykdaAoiTZBJwQpHHQv6pZUye0',
    appId: '1:361449298229:android:7f2cc099abd032232b147c',
    messagingSenderId: '361449298229',
    projectId: 'furniture-hub-b0293',
    storageBucket: 'furniture-hub-b0293.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzoHCLEBCGYLgSoSlo9dYJnnzHH-XnIGk',
    appId: '1:361449298229:ios:a0aa6dafd8181f532b147c',
    messagingSenderId: '361449298229',
    projectId: 'furniture-hub-b0293',
    storageBucket: 'furniture-hub-b0293.firebasestorage.app',
    iosBundleId: 'com.example.furnitureEcomApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzoHCLEBCGYLgSoSlo9dYJnnzHH-XnIGk',
    appId: '1:361449298229:ios:a0aa6dafd8181f532b147c',
    messagingSenderId: '361449298229',
    projectId: 'furniture-hub-b0293',
    storageBucket: 'furniture-hub-b0293.firebasestorage.app',
    iosBundleId: 'com.example.furnitureEcomApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0JGMXkp4UXO08kKu8FxC3ap0wUkWV68o',
    appId: '1:361449298229:web:d2f936276c7a356e2b147c',
    messagingSenderId: '361449298229',
    projectId: 'furniture-hub-b0293',
    authDomain: 'furniture-hub-b0293.firebaseapp.com',
    storageBucket: 'furniture-hub-b0293.firebasestorage.app',
    measurementId: 'G-285VQB5EY1',
  );
}
